### ISSUE TITLE
Conda package

### ISSUE THREAD

**Issue by torressa** [Gurobi/gurobi-optimods#107]
From a user in the community post [unable to install gurobi-optimods using conda install command (PackageNotFound error) ](https://support.gurobi.com/hc/en-us/community/posts/16709527968913-unable-to-install-gurobi-optimods-using-conda-install-command-PackageNotFound-error-).
Would be cool to release the package on Conda.

**Comment by rluce** [comment]
One can install gurobi-optimods in any conda env through pip already, so nobody is locked out.  Publishing in a secondary channel (conda? conda-forge?) increases the bureaucratic burden of maintaining deployment chains, secrets, workflow, etc.
