### ISSUE TITLE
Missing option in line optimization mod documentation

### ISSUE THREAD

**Issue by simonbowly** [Gurobi/gurobi-optimods#150]
In the API reference for line optimization, the `shortest_paths` argument does not have a documentation entry.

See: https://gurobi-optimods.readthedocs.io/en/stable/api.html#gurobi_optimods.line_optimization.line_optimization

@Marika-K can you please add that detail to the docstring?

**Comment by Marika-K** [comment]
Hi @simonbowly, I am thinking about adding a third strategy to the line planning option. Then it might be better to change the bool parameter `shortest_paths`  into an enum `strategy`. 
Can I change this later when I add a new strategy? Or shall I update this already now (even if it is not clear when I enhance this optimod)?

**Comment by simonbowly** [comment]
It can always be changed later (if necessary, we can leave `shortest_paths` as an additional undocumented option for backwards compatibility). But I think that the documentation should cover all the options that are available now.
