### ISSUE TITLE
Two edges between two nodes not properly calculated

### ISSUE THREAD

**Issue by jsfreischuetz** [Gurobi/gurobi-optimods#155]
**Describe the bug**
When solving a min cost flow problem, and if two or more edges in the same direction exist between two nodes, only the last defined edge use used. This causes the wrong solution to be found in many cases.

Partially this is because DiGraph does not support this feature, but MultiDiGraph does, which is not supported by gurobi optimods. Pandas also has a similar problem because the from and to columns as set as keys.

**To Reproduce**
```python
from gurobi_optimods import datasets
from gurobi_optimods.min_cost_flow import min_cost_flow_networkx
from networkx import DiGraph

G: DiGraph = datasets.simple_graph_networkx()
G.add_edge(2, 3, capacity=10, cost=-100)
G.add_edge(2, 3, capacity=1, cost=100)

obj, sol = min_cost_flow_networkx(G)
print(list(sol.edges(data=True)))
```

The first edge that is added is not used because it is overwritten by the second edge added.

**Expected behavior**
All three edges would be considered for flow rather than just the last flow defined for that path.

**Additional context**
gurobi-optimods v2.1.0
python v3.10.13

**Comment by jsfreischuetz** [comment]
Draft of one possible solution with #156

**Comment by simonbowly** [comment]
Thanks for raising this @jsfreischuetz. Definitely would make sense to handle these cases, I'll take a look at your PR.
