### ISSUE TITLE
Optimal Power Flow (OPF)

### ISSUE THREAD

**Issue by JaromilNajman** [Gurobi/gurobi-optimods#42]
**Why this Mod?**
We want to enable usage of Gurobi in the Power industry. Criteria:

- Solve model, get solution (no follow up analysis, e.g. IIS)
- Stateless: data-in data-out, no follow-up optimization steps
  - Model can be kept in memory for the purpose of returning solutions
- Covers a well-known concept from a non-optimization field
  - In particular, we must be able to explain what the Mod does using domain-specific terminology
- Clear purpose / single focus
  - There may be natural parameters to switch on/off various side-constraints, but these should be kept to a minimum

**What will the API be?**
Custom format.

**Additional context**
Any other details that should be communicated in the Mod writeup to help users/readers understanding?

Add detailed information about the relaxations and terminology used for ACOPF.

**Comment by ShaohuiLiu** [comment]
Hello, our team is very interested in this case and wondering when the OPF mod will be released? BTW is this mod the same withe the one mentioned in the (attached link) seminar? Thx!
[https://www.gurobi.com/events/the-ac-optimal-power-flow-problem/?utm_source=gurobi&utm_medium=email&utm_campaign=2023+academics&utm_content=academic_webinar_invitation&mkt_tok=MTgxLVpZUy0wMDUAAAGLPmDTAreO45vtfJ19HZHraq9hiMaL-uE4YspoEACeeRMIeEQo9z2CWqv7MGsZqWpt7dbkhacjZ9mN0Q4LJ2sB4nJMZ9tor86iEIztlMOhxeo](url)

**Comment by simonbowly** [comment]
@ShaohuiLiu thanks for your interest. We still have some work to do for this one, but aim to have it included in the OptiMods in the next month or so.

**Comment by simonbowly** [comment]
The Optimal Power Flow mod is now released with `gurobi-optimods` version 1.1.0. Please see the documentation here: https://gurobi-optimization-gurobi-optimods.readthedocs-hosted.com/en/stable/mods/opf/opf.html
